# Generated by Django 4.1 on 2022-08-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('poisoning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('dislike_post', models.ManyToManyField(blank=True, default=None, related_name='dislike', to=settings.AUTH_USER_MODEL)),
                ('like_post', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_like', models.CharField(choices=[('Like', 'Like'), ('Like', 'Like')], default='Like', max_length=10)),
                ('post_likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='fungus.post')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_dislike', models.CharField(choices=[('Dislike', 'Dislike'), ('Dislike', 'Dislike')], default='Dislike', max_length=10)),
                ('post_dislikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dislike', to='fungus.post')),
                ('user_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
