# Generated by Django 4.1 on 2022-08-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungus', '0004_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-posted']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='owner',
        ),
    ]
