# Generated by Django 4.1 on 2022-08-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungus', '0005_alter_message_options_rename_host_room_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-added']},
        ),
    ]
